# Generated by Django 5.2.1 on 2025-05-30 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0003_alter_cardapio_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardapio',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cardapio',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/'),
        ),
    ]
